// All keys/fields a user can utlize within a filter.
// Value = the index of the player object to select.
export const playersSearchFilter: { title: string; value: string }[] = [
	{ title: "Citizen ID", value: "citizenId" },
	{ title: "Played By", value: "name" },
	{ title: "First Name", value: "charInfo.firstname" },
	{ title: "Last Name", value: "charInfo.lastname" },
	{ title: "License", value: "license" },
	{ title: "Cash", value: "money.cash" },
	{ title: "Bank", value: "money.bank" },
	{ title: "Crypto", value: "money.crypto" },
	{ title: "Phone Number", value: "phoneNumber" },
	{ title: "Gender", value: "charInfo.gender" },
	{ title: "account", value: "charInfo.account" },
	{ title: "Birth Date", value: "charInfo.birthdate" },
	{ title: "Nationality", value: "charInfo.nationality" },
	{ title: "Job Boss", value: "job.isboss" },
	{ title: "Job Name", value: "job.name" },
	{ title: "Job Label", value: "job.label" },
	{ title: "Job Type", value: "job.type" },
	{ title: "Job Pay", value: "job.payment" },
	{ title: "Job Duty", value: "job.onduty" },
	{ title: "Job Level", value: "job.grade.level" },
	{ title: "Job Level Name", value: "job.grade.name" },
	{ title: "Gang Name", value: "gang.name" },
	{ title: "Is Gang Boss", value: "gang.isboss" },
	{ title: "Gang Level", value: "gang.grade.level" },
	{ title: "Gang Level Name", value: "gang.grade.name" },
	{ title: "Gang Label", value: "gang.label" },
];
